-- Change true to false to disable a feature, then restart PAYDAY 2.
return {
    god_mode = true,
    unlimited_ammo = true,
    no_recoil = true,
    no_spread = true,
    unlimited_stamina = true,
    instant_mask = true,
    no_fall_damage = true,
    no_movement_penalty = true,
    shock_proof = true,
    flashbang_immunity = true,
    concussion_immunity = true,
    unlimited_cable_ties = true,
    unlimited_equipment = true,
    instant_deployment = true,
    instant_interactions = true,
    unlimited_pagers = true,
    no_drill_jamming = true,
    one_hit_kills = true,
    instant_weapon_swap = true,
    unlimited_sentry_ammo = true,
    unlimited_sentry_health = true,
    undetectable = false,
    keep_stealth = false,
    cops_no_shoot = false,
    auto_kill_spawns = false,
    instant_timers = false
}
